package Exceptions

fun erroneousCode(){
    //val i= "1$".toInt()
}
